<?php

/**
 * Template metadata for AI selection and Design Guard.
 *
 * Each template has: template_id (slug), verticals, vibes, quality_score,
 * hero_variants_supported, product_card_variants_supported.
 * AI must prefer templates with higher quality_score.
 *
 * @see new tasks.txt — Template Metadata + Governance, Design Guard PART 6
 */
return [
    'ecommerce-storefront' => [
        'template_id' => 'ecommerce-storefront',
        'verticals' => ['general', 'ecommerce'],
        'vibes' => ['modern', 'clean'],
        'density' => 'balanced',
        'quality_score' => 85,
        'hero_variants_supported' => ['centered', 'split', 'backgroundimage'],
        'product_card_variants_supported' => ['standard', 'compact', 'softshadow', 'outline'],
    ],
    'ecommerce-fashion' => [
        'template_id' => 'ecommerce-fashion',
        'verticals' => ['fashion'],
        'vibes' => ['luxury_minimal', 'modern'],
        'density' => 'balanced',
        'quality_score' => 90,
        'hero_variants_supported' => ['centered', 'backgroundimage', 'fashion_split_hero'],
        'product_card_variants_supported' => ['premium', 'standard', 'softshadow'],
    ],
    'ecommerce-electronics' => [
        'template_id' => 'ecommerce-electronics',
        'verticals' => ['electronics', 'tech'],
        'vibes' => ['corporate_clean', 'dark_modern'],
        'density' => 'balanced',
        'quality_score' => 88,
        'hero_variants_supported' => ['split', 'backgroundimage', 'classic'],
        'product_card_variants_supported' => ['compact', 'outline', 'standard'],
    ],
    'ecommerce-luxury-boutique' => [
        'template_id' => 'ecommerce-luxury-boutique',
        'verticals' => ['fashion', 'luxury', 'jewelry'],
        'vibes' => ['luxury_minimal'],
        'density' => 'comfortable',
        'quality_score' => 92,
        'hero_variants_supported' => ['centered', 'backgroundimage'],
        'product_card_variants_supported' => ['premium', 'softshadow'],
    ],
    'ecommerce-beauty' => [
        'template_id' => 'ecommerce-beauty',
        'verticals' => ['beauty'],
        'vibes' => ['luxury_minimal', 'soft_pastel'],
        'density' => 'balanced',
        'quality_score' => 89,
        'hero_variants_supported' => ['centered', 'split', 'backgroundimage'],
        'product_card_variants_supported' => ['premium', 'soft', 'softshadow'],
    ],
    'ecommerce-cosmetics' => [
        'template_id' => 'ecommerce-cosmetics',
        'verticals' => ['beauty', 'cosmetics'],
        'vibes' => ['luxury_minimal', 'soft_pastel'],
        'density' => 'balanced',
        'quality_score' => 88,
        'hero_variants_supported' => ['centered', 'backgroundimage'],
        'product_card_variants_supported' => ['premium', 'soft'],
    ],
    'ecommerce-pet' => [
        'template_id' => 'ecommerce-pet',
        'verticals' => ['pet'],
        'vibes' => ['bold_startup', 'playful'],
        'density' => 'balanced',
        'quality_score' => 87,
        'hero_variants_supported' => ['centered', 'split', 'backgroundimage'],
        'product_card_variants_supported' => ['standard', 'softshadow'],
    ],
    'ecommerce-kids' => [
        'template_id' => 'ecommerce-kids',
        'verticals' => ['kids'],
        'vibes' => ['soft_pastel', 'playful'],
        'density' => 'balanced',
        'quality_score' => 87,
        'hero_variants_supported' => ['centered', 'backgroundimage'],
        'product_card_variants_supported' => ['soft', 'standard'],
    ],
    'ecommerce-furniture' => [
        'template_id' => 'ecommerce-furniture',
        'verticals' => ['furniture', 'home_decor'],
        'vibes' => ['luxury_minimal', 'corporate_clean'],
        'density' => 'comfortable',
        'quality_score' => 88,
        'hero_variants_supported' => ['split', 'backgroundimage', 'centered'],
        'product_card_variants_supported' => ['premium', 'standard'],
    ],
    'ecommerce-jewelry' => [
        'template_id' => 'ecommerce-jewelry',
        'verticals' => ['jewelry', 'luxury'],
        'vibes' => ['luxury_minimal'],
        'density' => 'comfortable',
        'quality_score' => 91,
        'hero_variants_supported' => ['centered', 'backgroundimage'],
        'product_card_variants_supported' => ['premium'],
    ],
    'ecommerce-sports' => [
        'template_id' => 'ecommerce-sports',
        'verticals' => ['sports', 'sneaker'],
        'vibes' => ['bold_startup', 'dark_modern'],
        'density' => 'balanced',
        'quality_score' => 86,
        'hero_variants_supported' => ['backgroundimage', 'centered', 'classic'],
        'product_card_variants_supported' => ['standard', 'compact', 'outline'],
    ],
    'ecommerce-grocery' => [
        'template_id' => 'ecommerce-grocery',
        'verticals' => ['food', 'grocery', 'organic'],
        'vibes' => ['corporate_clean', 'soft_pastel'],
        'density' => 'balanced',
        'quality_score' => 85,
        'hero_variants_supported' => ['centered', 'split'],
        'product_card_variants_supported' => ['standard', 'compact'],
    ],
    'ecommerce-food-delivery' => [
        'template_id' => 'ecommerce-food-delivery',
        'verticals' => ['food'],
        'vibes' => ['bold_startup', 'modern'],
        'density' => 'balanced',
        'quality_score' => 85,
        'hero_variants_supported' => ['centered', 'backgroundimage'],
        'product_card_variants_supported' => ['standard', 'softshadow'],
    ],
    'ecommerce-soft-pastel' => [
        'template_id' => 'ecommerce-soft-pastel',
        'verticals' => ['beauty', 'kids'],
        'vibes' => ['soft_pastel'],
        'density' => 'comfortable',
        'quality_score' => 88,
        'hero_variants_supported' => ['centered', 'backgroundimage'],
        'product_card_variants_supported' => ['soft', 'premium'],
    ],
    'ecommerce-corporate-clean' => [
        'template_id' => 'ecommerce-corporate-clean',
        'verticals' => ['general', 'b2b'],
        'vibes' => ['corporate_clean'],
        'density' => 'balanced',
        'quality_score' => 86,
        'hero_variants_supported' => ['centered', 'split', 'classic'],
        'product_card_variants_supported' => ['standard', 'outline', 'compact'],
    ],
    'ecommerce-bold-startup' => [
        'template_id' => 'ecommerce-bold-startup',
        'verticals' => ['startup', 'tech'],
        'vibes' => ['bold_startup'],
        'density' => 'balanced',
        'quality_score' => 87,
        'hero_variants_supported' => ['centered', 'backgroundimage', 'classic'],
        'product_card_variants_supported' => ['standard', 'outline'],
    ],
    'ecommerce-dark-modern' => [
        'template_id' => 'ecommerce-dark-modern',
        'verticals' => ['electronics', 'gaming'],
        'vibes' => ['dark_modern'],
        'density' => 'balanced',
        'quality_score' => 88,
        'hero_variants_supported' => ['backgroundimage', 'centered'],
        'product_card_variants_supported' => ['outline', 'compact', 'standard'],
    ],
    'ecommerce-creative-boutique' => [
        'template_id' => 'ecommerce-creative-boutique',
        'verticals' => ['fashion', 'creative'],
        'vibes' => ['creative_portfolio'],
        'density' => 'balanced',
        'quality_score' => 88,
        'hero_variants_supported' => ['centered', 'split', 'backgroundimage'],
        'product_card_variants_supported' => ['premium', 'standard'],
    ],
    'ecommerce-minimal-startup' => [
        'template_id' => 'ecommerce-minimal-startup',
        'verticals' => ['startup', 'digital'],
        'vibes' => ['luxury_minimal', 'modern'],
        'density' => 'compact',
        'quality_score' => 86,
        'hero_variants_supported' => ['centered', 'minimal_centered'],
        'product_card_variants_supported' => ['standard', 'compact'],
    ],
    'ecommerce-digital' => [
        'template_id' => 'ecommerce-digital',
        'verticals' => ['digital_products'],
        'vibes' => ['modern', 'minimal'],
        'density' => 'compact',
        'quality_score' => 85,
        'hero_variants_supported' => ['centered', 'classic'],
        'product_card_variants_supported' => ['standard', 'compact'],
    ],
    // Section 9 — 50-template library (20 additional templates)
    'ecommerce-streetwear' => [
        'template_id' => 'ecommerce-streetwear',
        'verticals' => ['fashion', 'streetwear'],
        'vibes' => ['bold_startup'],
        'density' => 'balanced',
        'quality_score' => 86,
        'hero_variants_supported' => ['centered', 'backgroundimage'],
        'product_card_variants_supported' => ['outline', 'standard'],
    ],
    'ecommerce-sneaker' => [
        'template_id' => 'ecommerce-sneaker',
        'verticals' => ['sports', 'sneaker'],
        'vibes' => ['dark_modern'],
        'density' => 'balanced',
        'quality_score' => 87,
        'hero_variants_supported' => ['centered', 'backgroundimage'],
        'product_card_variants_supported' => ['outline', 'compact'],
    ],
    'ecommerce-watches' => [
        'template_id' => 'ecommerce-watches',
        'verticals' => ['jewelry', 'luxury'],
        'vibes' => ['luxury_minimal'],
        'density' => 'comfortable',
        'quality_score' => 90,
        'hero_variants_supported' => ['centered', 'backgroundimage'],
        'product_card_variants_supported' => ['premium', 'standard'],
    ],
    'ecommerce-skincare' => [
        'template_id' => 'ecommerce-skincare',
        'verticals' => ['beauty', 'cosmetics'],
        'vibes' => ['soft_pastel'],
        'density' => 'balanced',
        'quality_score' => 88,
        'hero_variants_supported' => ['centered', 'minimal_centered'],
        'product_card_variants_supported' => ['soft', 'premium'],
    ],
    'ecommerce-makeup-studio' => [
        'template_id' => 'ecommerce-makeup-studio',
        'verticals' => ['beauty', 'cosmetics'],
        'vibes' => ['creative_portfolio', 'bold_startup'],
        'density' => 'balanced',
        'quality_score' => 87,
        'hero_variants_supported' => ['split', 'centered', 'backgroundimage'],
        'product_card_variants_supported' => ['premium', 'standard'],
    ],
    'ecommerce-gaming' => [
        'template_id' => 'ecommerce-gaming',
        'verticals' => ['electronics', 'gaming'],
        'vibes' => ['dark_modern'],
        'density' => 'balanced',
        'quality_score' => 86,
        'hero_variants_supported' => ['centered', 'backgroundimage'],
        'product_card_variants_supported' => ['dense', 'outline', 'compact'],
    ],
    'ecommerce-smart-home' => [
        'template_id' => 'ecommerce-smart-home',
        'verticals' => ['electronics', 'tech'],
        'vibes' => ['corporate_clean'],
        'density' => 'balanced',
        'quality_score' => 85,
        'hero_variants_supported' => ['split', 'centered'],
        'product_card_variants_supported' => ['clean', 'compact'],
    ],
    'ecommerce-phone-store' => [
        'template_id' => 'ecommerce-phone-store',
        'verticals' => ['electronics', 'tech'],
        'vibes' => ['corporate_clean'],
        'density' => 'balanced',
        'quality_score' => 85,
        'hero_variants_supported' => ['centered', 'classic'],
        'product_card_variants_supported' => ['compact', 'standard'],
    ],
    'ecommerce-scandinavian' => [
        'template_id' => 'ecommerce-scandinavian',
        'verticals' => ['furniture', 'home_decor'],
        'vibes' => ['luxury_minimal'],
        'density' => 'comfortable',
        'quality_score' => 89,
        'hero_variants_supported' => ['centered', 'minimal_centered'],
        'product_card_variants_supported' => ['premium', 'standard'],
    ],
    'ecommerce-lighting' => [
        'template_id' => 'ecommerce-lighting',
        'verticals' => ['furniture', 'home_decor'],
        'vibes' => ['luxury_minimal'],
        'density' => 'balanced',
        'quality_score' => 86,
        'hero_variants_supported' => ['centered', 'backgroundimage'],
        'product_card_variants_supported' => ['premium', 'standard'],
    ],
    'ecommerce-kitchen-dining' => [
        'template_id' => 'ecommerce-kitchen-dining',
        'verticals' => ['food', 'home_decor'],
        'vibes' => ['soft_pastel', 'corporate_clean'],
        'density' => 'balanced',
        'quality_score' => 85,
        'hero_variants_supported' => ['centered', 'split'],
        'product_card_variants_supported' => ['standard', 'softshadow'],
    ],
    'ecommerce-dog-accessories' => [
        'template_id' => 'ecommerce-dog-accessories',
        'verticals' => ['pet'],
        'vibes' => ['bold_startup', 'playful'],
        'density' => 'balanced',
        'quality_score' => 85,
        'hero_variants_supported' => ['centered', 'split'],
        'product_card_variants_supported' => ['standard', 'softshadow'],
    ],
    'ecommerce-cat-store' => [
        'template_id' => 'ecommerce-cat-store',
        'verticals' => ['pet'],
        'vibes' => ['soft_pastel', 'playful'],
        'density' => 'balanced',
        'quality_score' => 85,
        'hero_variants_supported' => ['centered', 'backgroundimage'],
        'product_card_variants_supported' => ['soft', 'standard'],
    ],
    'ecommerce-pet-food' => [
        'template_id' => 'ecommerce-pet-food',
        'verticals' => ['pet', 'food'],
        'vibes' => ['corporate_clean'],
        'density' => 'balanced',
        'quality_score' => 85,
        'hero_variants_supported' => ['centered', 'split'],
        'product_card_variants_supported' => ['clean', 'standard'],
    ],
    'ecommerce-educational-toys' => [
        'template_id' => 'ecommerce-educational-toys',
        'verticals' => ['kids'],
        'vibes' => ['soft_pastel', 'playful'],
        'density' => 'balanced',
        'quality_score' => 86,
        'hero_variants_supported' => ['centered', 'minimal_centered'],
        'product_card_variants_supported' => ['soft', 'standard'],
    ],
    'ecommerce-outdoor' => [
        'template_id' => 'ecommerce-outdoor',
        'verticals' => ['sports', 'outdoor'],
        'vibes' => ['bold_startup'],
        'density' => 'balanced',
        'quality_score' => 86,
        'hero_variants_supported' => ['centered', 'backgroundimage'],
        'product_card_variants_supported' => ['outline', 'standard'],
    ],
    'ecommerce-fitness' => [
        'template_id' => 'ecommerce-fitness',
        'verticals' => ['sports', 'fitness'],
        'vibes' => ['dark_modern'],
        'density' => 'balanced',
        'quality_score' => 85,
        'hero_variants_supported' => ['centered', 'backgroundimage'],
        'product_card_variants_supported' => ['dense', 'compact'],
    ],
    'ecommerce-supplements' => [
        'template_id' => 'ecommerce-supplements',
        'verticals' => ['wellness', 'sports'],
        'vibes' => ['corporate_clean'],
        'density' => 'balanced',
        'quality_score' => 85,
        'hero_variants_supported' => ['centered', 'classic'],
        'product_card_variants_supported' => ['clean', 'standard'],
    ],
    'ecommerce-coffee' => [
        'template_id' => 'ecommerce-coffee',
        'verticals' => ['food', 'grocery'],
        'vibes' => ['dark_modern'],
        'density' => 'balanced',
        'quality_score' => 86,
        'hero_variants_supported' => ['centered', 'backgroundimage'],
        'product_card_variants_supported' => ['standard', 'softshadow'],
    ],
    'ecommerce-tea' => [
        'template_id' => 'ecommerce-tea',
        'verticals' => ['food', 'grocery'],
        'vibes' => ['soft_pastel'],
        'density' => 'balanced',
        'quality_score' => 85,
        'hero_variants_supported' => ['centered', 'minimal_centered'],
        'product_card_variants_supported' => ['soft', 'standard'],
    ],
    // Fallbacks for catalog slugs (Director uses these when slug is referenced)
    // Section 8: optional required_components (conceptual: Hero, CategoryGrid, ProductGrid, NewsletterSignup, Footer)
    'ecommerce' => [
        'template_id' => 'ecommerce',
        'verticals' => ['general', 'ecommerce'],
        'vibes' => ['luxury_minimal', 'modern'],
        'density' => 'balanced',
        'quality_score' => 85,
        'hero_variants_supported' => ['centered', 'split', 'backgroundimage'],
        'product_card_variants_supported' => ['standard', 'compact', 'softshadow'],
        'required_components' => ['Hero', 'ProductGrid', 'NewsletterSignup', 'Footer'],
    ],
    'default' => [
        'template_id' => 'default',
        'verticals' => ['general', 'ecommerce'],
        'vibes' => ['luxury_minimal'],
        'density' => 'balanced',
        'quality_score' => 80,
        'hero_variants_supported' => ['centered'],
        'product_card_variants_supported' => ['standard'],
        'required_components' => ['Hero', 'ProductGrid', 'Footer'],
    ],
];
