<?php

namespace Tests\Unit;

use Illuminate\Support\Facades\File;
use Tests\TestCase;

class BuilderServicePublicVerticalRuntimeHelpersContractTest extends TestCase
{
    public function test_builder_service_exposes_public_vertical_and_booking_runtime_helper_contracts(): void
    {
        $path = base_path('app/Services/BuilderService.php');
        $this->assertFileExists($path);

        $source = File::get($path);

        foreach ([
            "'service_detail_url_pattern' =>",
            "'staff_url' =>",
            "'calendar_url' =>",
            "'my_bookings_url' =>",
            "'booking_url_pattern' =>",
            "'pricing_url' =>",
            "'faq_url' =>",
            "'services_selector' => '[data-webby-booking-services]'",
            "'service_detail_selector' => '[data-webby-booking-service-detail]'",
            "'pricing_table_selector' => '[data-webby-booking-pricing-table]'",
            "'faq_selector' => '[data-webby-booking-faq]'",
            "'form_selector' => '[data-webby-booking-form]'",
            "'slots_selector' => '[data-webby-booking-slots]'",
            "'calendar_selector' => '[data-webby-booking-calendar]'",
            "'staff_selector' => '[data-webby-booking-staff]'",
            "'manage_selector' => '[data-webby-booking-manage]'",
            'function getService(slug) {',
            'function listStaff(params) {',
            'function getCalendar(params) {',
            'function getBookings(params) {',
            'function showBooking(bookingId) {',
            'function updateBooking(bookingId, payload) {',
            'function rescheduleBooking(bookingId, payload) {',
            'function cancelBooking(bookingId, payload) {',
            'function mountServicesWidget(container, options) {',
            'function mountServiceDetailWidget(container, options) {',
            'function mountPricingTableWidget(container, options) {',
            'function mountFaqWidget(container, options) {',
            'function mountSlotsWidget(container, options) {',
            'function mountCalendarWidget(container, options) {',
            'function mountStaffWidget(container, options) {',
            'function mountManageWidget(container, options) {',
            'getService: getService,',
            'listStaff: listStaff,',
            'getCalendar: getCalendar,',
            'getBookings: getBookings,',
            'showBooking: showBooking,',
            'updateBooking: updateBooking,',
            'rescheduleBooking: rescheduleBooking,',
            'cancelBooking: cancelBooking,',
            'mountBookingFormWidget: mountWidget,',
            'window.WebbyPortfolio = window.WebbyPortfolio || {};',
            'window.WebbyPortfolio.listProjects = function () { return cmsPublicJson(\'/portfolio\'); };',
            'window.WebbyPortfolio.getProject = function (slug) { return cmsPublicJson(\'/portfolio/\' + encodeURIComponent(String(slug || \'\'))); };',
            'window.WebbyPortfolio.mountProjectsWidget = mountPortfolioProjectsWidget;',
            'window.WebbyPortfolio.mountProjectDetailWidget = mountPortfolioProjectDetailWidget;',
            'window.WebbyPortfolio.mountGalleryWidget = mountPortfolioGalleryWidget;',
            'window.WebbyBlog = window.WebbyBlog || {};',
            "window.WebbyBlog.listPosts = function (params) {",
            "window.WebbyBlog.getPost = function (slug) { return cmsPublicJson('/posts/' + encodeURIComponent(String(slug || ''))); };",
            "window.WebbyBlog.listCategories = function () { return cmsPublicJson('/post-categories'); };",
            'window.WebbyBlog.mountPostListWidget = mountBlogPostListWidget;',
            'window.WebbyBlog.mountPostDetailWidget = mountBlogPostDetailWidget;',
            'window.WebbyBlog.mountCategoryListWidget = mountBlogCategoryListWidget;',
            'mountBlogPostListWidget(container)',
            'mountBlogPostDetailWidget(container)',
            'mountBlogCategoryListWidget(container)',
            'window.WebbyRealEstate = window.WebbyRealEstate || {};',
            'window.WebbyRealEstate.listProperties = function (params) { return realEstateListProperties(params); };',
            "window.WebbyRealEstate.getProperty = function (slug) { return cmsPublicJson('/properties/' + encodeURIComponent(String(slug || ''))); };",
            'window.WebbyRealEstate.mountPropertiesWidget = mountRealEstatePropertiesWidget;',
            'window.WebbyRealEstate.mountPropertyDetailWidget = mountRealEstatePropertyDetailWidget;',
            'window.WebbyRealEstate.mountMapWidget = mountRealEstateMapWidget;',
            'function realEstateListProperties(params) {',
            'function normalizeRealEstateMapProvider(value) {',
            'function mountRealEstatePropertiesWidget(container, options) {',
            'function mountRealEstateMapWidget(container, options) {',
            'data-webby-realestate-map-provider',
            'data-webby-realestate-map-marker',
            'Map provider: ',
            'window.WebbyRestaurant = window.WebbyRestaurant || {};',
            'function restaurantListMenuItems(params) {',
            "['category', 'category_id'].forEach(function (key) {",
            "return cmsPublicJson('/restaurant/menu/items' + (query.toString() ? ('?' + query.toString()) : ''));",
            'function mountRestaurantMenuCategoriesWidget(container) {',
            'function mountRestaurantMenuItemsWidget(container, options) {',
            'function mountRestaurantReservationWidget(container) {',
            "container.getAttribute('data-webby-restaurant-' + key.replace(/_/g, '-'))",
            "window.WebbyRestaurant.listMenuCategories = function () { return cmsPublicJson('/restaurant/menu'); };",
            'window.WebbyRestaurant.listMenuItems = function (params) { return restaurantListMenuItems(params); };',
            "window.WebbyRestaurant.createReservation = function (payload) { return cmsPublicJsonPost('/restaurant/reservations', payload); };",
            'window.WebbyRestaurant.mountMenuCategoriesWidget = mountRestaurantMenuCategoriesWidget;',
            'window.WebbyRestaurant.mountMenuItemsWidget = mountRestaurantMenuItemsWidget;',
            'window.WebbyRestaurant.mountReservationFormWidget = mountRestaurantReservationWidget;',
            'window.WebbyHotel = window.WebbyHotel || {};',
            'function hotelListRooms(params) {',
            "['q', 'capacity', 'limit'].forEach(function (key) {",
            "return cmsPublicJson('/rooms' + (query.toString() ? ('?' + query.toString()) : ''));",
            'function mountHotelRoomsWidget(container, options) {',
            "container.getAttribute('data-webby-hotel-' + key.replace(/_/g, '-'))",
            'function mountHotelRoomWidget(container) {',
            'function mountHotelAvailabilityWidget(container) {',
            'function mountHotelReservationWidget(container) {',
            "window.WebbyHotel.listRooms = function (params) { return hotelListRooms(params); };",
            "window.WebbyHotel.getRoom = function (id) { return cmsPublicJson('/rooms/' + encodeURIComponent(String(id || ''))); };",
            "window.WebbyHotel.createReservation = function (payload) { return cmsPublicJsonPost('/room-reservations', payload); };",
            'window.WebbyHotel.mountRoomsWidget = mountHotelRoomsWidget;',
            'window.WebbyHotel.mountRoomWidget = mountHotelRoomWidget;',
            'window.WebbyHotel.mountAvailabilityWidget = mountHotelAvailabilityWidget;',
            'window.WebbyHotel.mountReservationFormWidget = mountHotelReservationWidget;',
            'data-webby-hotel-room-id-input',
            'data-webby-hotel-checkin',
            'data-webby-hotel-checkout',
            'data-webby-hotel-submit',
            'data-webby-hotel-message',
            'data-webby-portfolio-gallery-grid',
            'data-webby-portfolio-gallery-slider',
            'data-webby-portfolio-gallery-lightbox',
            'data-webby-portfolio-gallery-lightbox-trigger',
            'data-webby-portfolio-lightbox-close',
            '[data-webby-portfolio-projects]',
            '[data-webby-portfolio-project-detail]',
            '[data-webby-portfolio-gallery]',
            '[data-webby-blog-post-list]',
            '[data-webby-blog-post-detail]',
            '[data-webby-blog-category-list]',
            '[data-webby-realestate-properties]',
            '[data-webby-realestate-property-detail]',
            '[data-webby-realestate-map]',
            '[data-webby-restaurant-menu-categories]',
            '[data-webby-restaurant-menu-items]',
            '[data-webby-restaurant-reservation-form]',
            '[data-webby-hotel-rooms]',
            '[data-webby-hotel-room]',
            '[data-webby-hotel-availability]',
            '[data-webby-hotel-reservation-form]',
            "'customer_me_url' =>",
            "'customer_login_url' =>",
            "'customer_register_url' =>",
            "'customer_logout_url' =>",
            "'customer_me_update_url' =>",
            "'auth_otp_request_url' =>",
            "'auth_otp_verify_url' =>",
            "'auth_google_url' =>",
            "'auth_facebook_url' =>",
            "'auth_selector' => '[data-webby-ecommerce-auth]'",
            "'account_profile_selector' => '[data-webby-ecommerce-account-profile]'",
            "'account_security_selector' => '[data-webby-ecommerce-account-security]'",
            'function customerLogin(payload) {',
            'function customerRegister(payload) {',
            'function customerLogout(payload) {',
            'function customerMeUpdate(payload) {',
            'function customerOtpRequest(payload) {',
            'function customerOtpVerify(payload) {',
            'function customerSocialAuthStart(provider, payload) {',
            'window.WebbyEcommerce.mountAuthWidget = mountAuthWidget;',
            'window.WebbyEcommerce.mountAccountProfileWidget = mountAccountProfileWidget;',
            'window.WebbyEcommerce.mountAccountSecurityWidget = mountAccountSecurityWidget;',
            'window.WebbyEcommerce.getCustomerMe = customersMe;',
            'window.WebbyEcommerce.loginCustomer = customerLogin;',
            'registerCustomer: customerRegister,',
            'logoutCustomer: customerLogout,',
            'window.WebbyEcommerce.updateCustomerMe = customerMeUpdate;',
            'window.WebbyEcommerce.requestOtp = customerOtpRequest;',
            'window.WebbyEcommerce.verifyOtp = customerOtpVerify;',
            "window.WebbyEcommerce.startGoogleAuth = function (payload) { return customerSocialAuthStart('google', payload); };",
            "window.WebbyEcommerce.startFacebookAuth = function (payload) { return customerSocialAuthStart('facebook', payload); };",
            '/customers/me',
            '/customers/login',
            '/auth/otp/request',
            '/auth/otp/verify',
            "/auth/' + encodeURIComponent(String(provider || ''))",
        ] as $needle) {
            $this->assertStringContainsString($needle, $source);
        }
    }
}
